# Generated by Django 4.1.3 on 2022-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_stock_table_price_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_price_table',
            name='date_time',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='stock_table',
            name='added_at',
            field=models.CharField(max_length=11),
        ),
    ]
